### ISSUE TITLE
"Moms klass för faktura avgift" should be "Momsklass för fakturaavgift"

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#136]

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by Aviree** [comment]
Downloaded the latest 2.2 version and did the test. Still not working. 
![moms_klass_fakt](https://cloud.githubusercontent.com/assets/14887835/12171275/b7cd192c-b548-11e5-8fbf-c3453ba088f7.PNG)

**Comment by Aviree** [comment]
With the latest update this looks correct.
Close this issue
