### ISSUE TITLE
partpay should not be visible if invoice fee make total over min amount

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/woocommerce#141]

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by Aviree** [comment]
I tested this function and it still an issue. My carts value is 1400. I put the minimum limit to 1405 on partpayment. When I choose Invoice, then partpayment appears because the new value is 1420. When I choose partpayment, it disappears.

**Comment by Boxedsolutions** [comment]
seems to work. I put 450 att lower limit, when the carts value was 448, activated billmate invoice and it was still invisible.

**Comment by Aviree** [comment]
Works fine 
Closing issue
