### ISSUE TITLE
Using severald decimals in invoice fee

### ISSUE THREAD

**Issue by victorauren** [Billmate/woocommerce#179]
When using invoice fee 23.201 the error "Total Summa med Skatt \u00e4r inte lika med Total Summa Exklusive Moms, Total Skatt och Avrundning.Ber\u00e4knat totalt" apperars. Works with two decimals but not three. 

Should be fixed if possible

298307

**Comment by Boxedsolutions** [comment]
SHould be fixed

**Comment by victorauren** [comment]
Still a problem. 
logid:312624

![rounding_woo](https://cloud.githubusercontent.com/assets/14887835/14308983/c4f02aae-fbd9-11e5-8a68-4c0be87db3ec.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by victorauren** [comment]
It works fine
closing issue
