### ISSUE TITLE
Automatically update PClasses

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#5]
Write a function that automatically updates all the PClasses, once a week.

**Comment by Boxedsolutions** [comment]
Its now implemented so that when a payment plan is about to expire it will update payment plans.

**Comment by andyjohansson** [comment]
Can you test and verify this @joakim-combain?

**Comment by joakim-combain** [comment]
I changed the keys to an account that should have expired pclasses. In our api-integration page it works but it doesn't work in the store. It seems to always load the old pclasses.

![installningar billmate](https://cloud.githubusercontent.com/assets/10434920/7275739/e10dda52-e905-11e4-8844-9734e6db4da0.png)

**Comment by Boxedsolutions** [comment]
Should be working now to automatically update

**Comment by joakim-combain** [comment]
This is still not working like it should. I changed keys, updated pclasses, got the correct pclasses. Then I changed one of the outdated pclasses so it would be active again. If I now press update pclasses again it still shows me the three standard ones that was loaded when my pclasses had expired. I tested in the spec and it works there.

**Comment by Boxedsolutions** [comment]
Which keys have outdated pclasses? So I could reproduce and solve it.

**Comment by joakim-combain** [comment]
9495 828885158288 the account is Billmate Demo.

**Comment by Boxedsolutions** [comment]
I have tested on the api-integration page and couldnt get outdated plans. I have in my mind that the API wouldnt return outdated plans. I could manually change it so it become outdated. To see if it autmatically updates with new plans when go to checkout or the product view.

**Comment by joakim-combain** [comment]
That's how I have done. I changed the pclass to be outdated, loaded the pclasses, then changed it back so it's active again and tried to update the pclasses, but it didn't work. I'm also not sure how this is supposed to work, It might not even be designed for the update pclasses button to load the new pclasses, maybe only if I go to a product view or checkout?

**Comment by Boxedsolutions** [comment]
The automatic update is supposed to check so that the pclasses is not expired in the frontend, and if it is. It tries to update the pclasses from the frontend, to make it available with the most recent pclasses. 

One way that may work to test it would be if you change the dates so it outdated, then update pclasses in Woocommerce backend. Then change the dates to be valid and try to visit either checkout or product page. To see if it did update the pclasses in Woocommerce backend, then it will work

**Comment by joakim-combain** [comment]
There seems to be some cashing on the site or something because I'm not able to load the new pclasses, even if I change to opencart keys first and then revert back to the other keys, which now should have a valid pclass. Seems like it's remembering my keys and automatically fetches the default pclasses. Is this working for you?

**Comment by Boxedsolutions** [comment]
What does the log say? I find it strange. The Api-integration page shows:
{
			"paymentplanid": "59",
			"description": "Test Billmate",
			"nbrofmonths": "3",
			"startfee": "10000",
			"handlingfee": "10000",
			"minamount": "10000",
			"maxamount": "1000000",
			"country": "se",
			"type": "1",
			"expirydate": "2015-12-30",
			"interestrate": "12",
			"currency": "SEK",
			"language": "sv",
			"totalfee": "912",
			"monthlycost": "30400"
		}

Which is not outdated. But we are getting the standards.

**Comment by joakim-combain** [comment]
That's the weird thing, it doesn't look like you are making any new requests to getpaymentplans. When I try it in api-integration it makes a new log but not if I press Update pclasses in the store. Also not updating in the product view.

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-04-29 15 23 49](https://cloud.githubusercontent.com/assets/8977650/7391776/c89866ee-ee83-11e4-9631-8e50b603783d.png)
Could it be the API that cache the request in some way?

**Comment by joakim-combain** [comment]
Might be, but then it shouldn't be making a new request from api-integration page and making a new log...

**Comment by andyjohansson** [comment]
Will check this with API developer today.
