### ISSUE TITLE
3.9 - I put an order with invoice, but the to pay sums are different in store and in bo.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#72]
Apilogsid: 33554
Invoice number: 32
Account: Billmate Demo

In store it says 708.27 but in BO it says 710,34.

I used 123åäö as discount.

**Comment by joakim-combain** [comment]
This issue is on our side. We can't handle 12% vat on handling fee apparently.

**Comment by Boxedsolutions** [comment]
Is it possible to get it working on your side? It feels rather hacky to implement logic if its 25 or not? I could do it though but wonder if a solution on your side is better?

**Comment by joakim-combain** [comment]
No, I'm putting it as an issue for out programmer to fix. We should handle all vat rates or not require vat at all. I think we should handle all of them atleast.

**Comment by andyjohansson** [comment]
You send in taxrate with 12.0000, should be sent in as 12 only. See API log id 57368.

**Comment by andyjohansson** [comment]
Will also be fixed in API level.

**Comment by Boxedsolutions** [comment]
What if the client sells to a country with taxrate with decimals?

**Comment by andyjohansson** [comment]
Look at that API log id. Why would we send it one way on product level and one way on invoice fee?

**Comment by Boxedsolutions** [comment]
I cast to float on product, seems to missed that on invoice fee.

**Comment by andyjohansson** [comment]
Ok, tell me when it´s fixed so we can close it =)

**Comment by Boxedsolutions** [comment]
should be fixed

**Comment by andyjohansson** [comment]
Still not? See API log id 57394. Or was it not uploaded? Also see test invoice id 323516.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by Boxedsolutions** [comment]
Tested a order, seems working

**Comment by andyjohansson** [comment]
Will verify it now.

**Comment by andyjohansson** [comment]
Fixed.
